### ISSUE TITLE
UpdateChecker leaks reference to activity.

### ISSUE THREAD

**Issue by mwinters-stuff** [pietrorampini/UpdateChecker#113]
Hi..

UpdateChecker leaks the reference to the activity that is passed in the call to
new UpdateChecker(this);

This was found using square's leakcanary

**Comment by rampo** [comment]
Thank you, I'll fix it soon

**Comment by akshath** [comment]
Hi,

any date for M2.1.9 ? 

Thanks

**Comment by falcon4ever** [comment]
Any updates?

**Comment by enochN** [comment]
Hello. Please any updates?
